# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb",
         "Deck": "00_card.ipynb",
         "Hand": "00_card.ipynb",
         "find_defining_class": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://ylchan87.github.io/deck_of_cards/"

git_url = "https://github.com/ylchan87/deck_of_cards/tree/{branch}/"

def custom_doc_links(name): return None
